/* eslint-disable */
/**
 * Generated API stub for Convex functions.
 * This file is committed as a build stub — the real version is generated by
 * `npx convex deploy`. In production (Vercel), the vercel.json buildCommand
 * runs `npx convex deploy` first, which overwrites this file with the real one.
 */
import { anyApi } from "convex/server";

export const api = anyApi as unknown as {
  activity: {
    list: any;
    log: any;
    search: any;
  };
  cronJobs: {
    list: any;
    upsert: any;
    remove: any;
  };
  documents: {
    list: any;
    upsert: any;
    search: any;
  };
};

export const internal = anyApi as unknown as Record<string, never>;
